version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
